const eventsContent = {
  header: {
    title: "Our Events",
    description:
      "We have a plethora of events that grooms an individual booth in the professional domain and the personal domain.Be it the DSA Marathon or Development, ML and Design Workshops or any other technical domain, we stand high on the zenith.Be it the physical activities, we have CSS Olympics always raising one's sportsmanship. You think of cultural fests, we have the ESPERANZA, CSS GO and many more bullets of enjoyment in our arsenal with our annual week CSS ABACUS being the head honcho, the Mother of Festivals always making an example set in stone. You name an event, we have it. Our dedicated team with the motto of PARTICIPATE ENJOY AND LEARN makes the events which makes an individual an All-Rounder and his/her moments of life unforgettable an exciting.",
  },
  body: {
    events: [
      {
        id: 1,
        section: "Yearly",
        name: "Abacus",
        slug: "abacus",
        description:
          "ABACUS is the flagship CSE fest packed with competitions, games, and challenges. It’s not just about winning prizes but also about showcasing ideas, with freshers getting the unique chance to step up as organizers. A week of fun, learning, and unforgettable memories!",
        status: "upcoming",
        date: "",
        venue: "CSE Department & Campus Grounds",
        event_flow: "1. Inaugural Ceremony & Keynote Address\n2. Commencement of Technical and Non-technical Events\n3. CSS Hacks & Datathon Pitching Sessions\n4. Latent Talent Show & Cultural Night\n5. Closing Ceremony & Prize Distribution",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dp4sknsba/image/upload/v1765813731/Screenshot_2025-12-15_211821_di46p1.png",
        moreEvents: [
          {
            name: "CSS Hacks",
            slug: "css-hacks",
            description: "CSS Hacks, the ultimate web development hackathon under ABACUS, and this time, the grid is charged with cyberpunk energy.Brainstorm. Break into the mainframe of creativity and pitch your most innovative ideas.",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "CSE Labs",
            event_flow: "1. Team Registration & Pitch Briefing\n2. 24-Hour Coding Marathon Commences\n3. Mid-way Mentoring Session\n4. Final Code Freeze & Pitch Submission\n5. Presentation & Judging Panel Review",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757500866/Screenshot_2025-09-10_161234_vx2ood.png",
          },
          {
            name: "Datathon",
            slug: "datathon",
            description: "Jack into the mainframe, sync your neural uplink, and brace yourself for a high-stakes descent into the raw pulse of data. The Neon Grid Datathon isn’t just a contest—it’s a warzone of intellect, where cyber-sleuths, AI tacticians, and code-warriors decrypt the future one dataset at a time.",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "CSE Seminar Hall",
            event_flow: "1. Dataset Reveal & Problem Statement Briefing\n2. Feature Engineering & Model Building Phase\n3. Intermediate Leaderboard Update\n4. Model Evaluation & Pipeline Submission\n5. Winners Announcement & Code Walkthrough",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757500751/Screenshot_2025-09-10_161038_eh5yh5.png",
          },
          {
            name: "Open Source Marathon",
            slug: "open-source-marathon",
            description: "With the Open Source Marathon, the Computer Science Society sets their sights on helping students explore the dark back-alleys of open-source software development, in the process, having them gang-up with their peers, and enabling them to build their empire in open-source software.",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "Online / Git & Github Labs",
            event_flow: "1. Introduction to Git & GitHub Workshop\n2. Project Repositories & Issues Announcement\n3. Pull Request Submissions & Reviews\n4. Leaderboard Updates & Final Code Reviews\n5. Closing and Contributor Recognition",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757499020/Screenshot_2025-09-10_154152_ypt8b8.png",
          },
          {
            name: "Treasure Hunt",
            slug: "treasure-hunt",
            description: "Get ready for the ultimate test of wit, teamwork, and strategy! Are you ready to decipher cryptic clues and claim The Final Paycheque? CSS brings you the most thrilling treasure hunt across the campus!",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "NITS Campus Grounds",
            event_flow: "1. Team Assembly & Rules Briefing\n2. First Clue Distribution\n3. Clue Tracing across Campus\n4. Final Clue Decryption\n5. Winning Team Crowned",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757501229/Screenshot_2025-09-10_161836_ma94ly.png",
          },
          {
            name: "Abacus Got Latent",
            slug: "abacus-got-latent",
            description: "Aspiring to become Samay Raina but don’t want to go to JAIL! Welcome to ‘ABACUS Got LATENT’, the ultimate talent showdown where self-awareness meets creativity! This is your chance to showcase your hidden talent- whether it’s dark comedy, mimicry, singing, acting, or any unique skill.",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "Main Auditorium",
            event_flow: "1. Participant Registration & Warm-up\n2. Round 1: Self-Awareness/Talent Showcase\n3. Panel Judging and Roast Session\n4. Round 2: Improvisation & Crowd Interaction\n5. Winner Declared & Trophy Presentation",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757501445/Screenshot_2025-09-10_162215_w81bsa.png",
          },
          {
            name: "Chase Cloud 9",
            slug: "chase-cloud-9",
            description: "Chase Cloud 9, an intense challenge brought by the Computer Science Society. It’s the ultimate test to find the next tech masterminds—designed to simulate the most rigorous real-world recruitment processes.",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "CSE Seminar Room",
            event_flow: "1. Round 1: Online Aptitude & Coding Assessment\n2. Round 2: Technical Interview Simulation\n3. Round 3: Group Discussion / Case Study Challenge\n4. Round 4: HR Interview Simulation\n5. Selection & Announcement of Tech Masterminds",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757501619/Screenshot_2025-09-10_162429_wexhhb.png",
          },
          {
            name: "Riddlex",
            slug: "riddlex",
            description: "Riddlex is here to put your wits to the test! No DSA, no CP—just pure mind-bending fun. Crack the code, claim the prize, and show the system who’s boss! Are you up for the challenge?",
            status: "upcoming",
            organizer: "Computer Science Society",
            date: "",
            venue: "CSE Labs & Online Discord",
            event_flow: "1. Decryption Rules & Riddle Hub Login\n2. Round 1: Cryptic Riddle Decoding\n3. Round 2: Cipher and Puzzle Solving\n4. Final Vault Decryption Challenge\n5. Announcement of the Riddle Master",
            registrationLink: null,
            "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/v1757501771/Screenshot_2025-09-10_162735_jjocgt.png",
          },
        ],
      },
      {
        id: 2,
        section: "Yearly",
        name: "Enigma",
        slug: "enigma",
        description:
          "ENIGMA introduces freshmen to the world of competitive programming through real-time coding challenges. It prepares students for internships and placements while sharpening problem-solving skills. Widely appreciated by alumni, this initiative from the CP Wing adds lasting value to every participant.",
        status: "upcoming",
        date: "",
        venue: "Online Coding Platforms / CSE Labs",
        event_flow: "1. Rules Briefing & Platform Sign-up\n2. 3-Hour Competitive Coding Contest\n3. Editorial Discussions & Solution Explanations\n4. Leaderboard Verification\n5. Announcement of Top Performers",
        organizer: "CP Wing",
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757498092/Screenshot_2025-09-10_152620_zjn6hp.png",
        registrationLink: null,
        moreEvents: null,
      },
      {
        id: 3,
        section: "Cultural",
        name: "Orientation",
        slug: "orientation",
        description: "The CSS organizes the official society orientation programme each year for the fresher batch.The program aims to make the students aware of the wide range of opportunities, events and programmes that society offers. It introduces the freshers to the various divisions and initiatives of the society",
        status: "upcoming",
        date: "",
        venue: "Main Auditorium",
        event_flow: "1. Welcome Address by Faculty Advisors\n2. Presentation on CSS History & Wings (DEV, CP, ML, Design, Sports)\n3. Speeches by Senior Executives & Alumni\n4. Q&A Session for Freshers\n5. High Tea & Interaction",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757497432/Screenshot_2025-09-10_151518_wda6tn.png",
      },
      {
        id: 4,
        section: "Cultural",
        name: "Esperanza",
        slug: "esperanza",
        description: "The official branch freshers for cse is organized by the CSS every year. The objective of the freshers is to provide the  students with a platform to interact with their batchmates and to kickstart their college journey with a bunch of fun and engaging events",
        status: "upcoming",
        date: "",
        venue: "Main Auditorium / Open Air Theatre",
        event_flow: "1. Lamp Lighting & Inaugural Dance\n2. Intro Round of Nominated Freshers\n3. Talent Show & Cultural Performances\n4. Rizz Show & Ramp Walk Final Round\n5. Crowning of Mr. & Ms. Freshers",
        organizer: "Computer Science Society",
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757496948/Esperanza_kagipt.png",
      },
      {
        id: 5,
        section: "Cultural",
        name: "The Inspire Room",
        slug: "the-inspire-room",
        description: "The Computer Science Society organizes numerous speaker sessions throughout the course of the year featuring techies from across the country. The words of guidance from the speakers target to ignite within the students a sense of zeal and initiative as they strive forward in their respective fields",
        organizer: "Computer Science Society",
        status: "upcoming",
        date: "",
        venue: "CSE Seminar Hall",
        event_flow: "1. Speaker Welcome & Introduction\n2. Keynote Talk on Industry Trends\n3. Live Interactive Q&A Session\n4. Memento Presentation\n5. Networking Session",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757497660/Screenshot_2025-09-10_151911_suipld.png",
      },
      {
        id: 6,
        section: "Cultural",
        name: "CSS Olympics",
        slug: "css-olympics",
        description: "CSS Olympics is the annual sports week conducted by the society and garners participation from all CSE batches. It provides a platform for the students to demonstrate their athletic abilities while participating in a wide range of sporting activities",
        status: "upcoming",
        date: "",
        venue: "College Sports Complex / Ground",
        event_flow: "1. Opening Ceremony & Batch March-Past\n2. Track & Field Events (100m, 200m, Relay)\n3. Team Sports (Cricket, Football, Volleyball)\n4. Indoor Sports (Table Tennis, Chess, Badminton)\n5. Prize Distribution Ceremony",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757497873/Screenshot_2025-09-10_152231_ytkhgh.png",
      },
      {
        id: 7,
        section: "Cultural",
        name: "CSS GO",
        slug: "css-go",
        description: "Being part of the society and it's legacy is an honour in no small sense.CSS organizes a plethora of fun events to commemorate the formation of society each year. The event is exclusively for second years CSE students and is organized by the second-year wing members themselves",
        status: "upcoming",
        date: "",
        venue: "CSE Courtyard",
        event_flow: "1. CSS GO Rollout & Rules Briefing\n2. Interactive Ice-breaking Games\n3. Technical Quiz & Memory Challenges\n4. Treasure Hunt & Fun Tasks\n5. Celebration & Group Photos",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757513693/Screenshot_2025-09-10_194534_ggzxbl.png",
      },
      {
        id: 8,
        section: "Cultural",
        name: "Farewell",
        slug: "farewell",
        description: "CSS organizes the farewell programme each year to bid adieu to the senior cse batch of the institute. The objective is to provide the seniors with a platform to relish and relive the joyous moments of their college lives and to honor their contributions to the institute and the student body",
        date: "",
        venue: "Main Auditorium",
        event_flow: "1. Welcoming the Senior Batch\n2. Nostalgic Video Montage & Speeches\n3. Cultural Performances by Juniors\n4. Titles & Mementos Distribution\n5. Farewell Dinner & DJ Session",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dp4sknsba/image/upload/v1760263115/farewell_dlwgfr.png",
      },
      {
        id: 9,
        section: "Technical",
        name: "Development Workshops",
        slug: "development-workshops",
        description: "CSS organizes numerous development workshops throughout the course of the year which are conducted by the DEV Wing to help the students navigate through the challenging concepts of fields like app dev, web dev, web3, etc.",
        status: "upcoming",
        date: "",
        venue: "CSE Lab 3",
        event_flow: "1. Topic Overview & Setup/Prerequisites Verification\n2. Live Coding & Concept Breakdown\n3. Guided Mini-project Implementation\n4. Q&A and Deployment Steps\n5. Sharing Resources & Feedback Forms",
        organizer: "DEV Wing",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757498715/Screenshot_2025-09-10_153618_jjkdfa.png",
      },
      {
        id: 10,
        section: "Technical",
        name: "ML Sessions",
        slug: "ml-sessions",
        description: "Machine Learning is one of the fastest-growing domains in computer science with several applications in data analytics. The ML wing of CSS organizes ML sessions on a regular basis to mentor students and help them advance in the field and pursue a career in it",
        status: "upcoming",
        date: "",
        venue: "CSE Seminar Room",
        event_flow: "1. Mathematical Foundations & Intuition Talk\n2. Jupyter Notebook / Google Colab Hands-on Coding\n3. Model Training & Evaluation Walkthrough\n4. Hyperparameter Tuning Tips\n5. Practical Use Cases Discussion",
        organizer: "ML Wing",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757497531/Screenshot_2025-09-10_151702_wk1qpm.png",
      },
      {
        id: 11,
        section: "Technical",
        name: "Open Source Marathon",
        slug: "open-source-marathon",
        description: "The Computer Science Society organizes hackathons throughout the course of the year which are open source.It is a great opportunity to get to know others that have the same interests and it is a great add up to your CV",
        status: "upcoming",
        date: "",
        venue: "GitHub / Online",
        event_flow: "1. Introductory Seminar on Open Source Contribution\n2. Open Repositories Announcement\n3. Contribution Period (Pull Request Submissions)\n4. PR Merges & Quality Audit\n5. Leaderboard Reveal & Rewards",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757498808/Screenshot_2025-09-10_153820_mfzwpl.png",
      },
      {
        id: 12,
        section: "Technical",
        name: "DSA Marathon",
        slug: "dsa-marathon",
        description: "The Computer Science Society organizes DSA marathon events to help the students improve their DSA skills which can help them in their carrerand improve their coding skills as well as in creating a competetive enviornment among the students",
        status: "upcoming",
        date: "",
        venue: "Online Hackerearth/LeetCode Platform",
        event_flow: "1. Contest Registration and Platform Walkthrough\n2. 4-Hour Intensive DSA Problem Solving\n3. Post-contest Editorial Session\n4. Code Walkthrough by Top Coders\n5. Rankings & Certificates Issuance",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757499143/Screenshot_2025-09-10_154354_r3r1nq.png",
      },
      {
        id: 13,
        section: "Technical",
        name: "Design Workshops",
        slug: "design-workshops",
        description: "The Computer Science Society organizes various design workshops throughout the year for the students thus helping them in improving their design skills in various fields",
        status: "upcoming",
        date: "",
        venue: "Figma Room / CSE Lab 1",
        event_flow: "1. Introduction to UI/UX Principles & Figma Layout\n2. Design Mockup Walkthrough\n3. Hands-on Component Creation\n4. Prototyping & Micro-animations Demonstration\n5. Design Peer Review & Feedback",
        organizer: "Design Wing",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757499342/Screenshot_2025-09-10_154712_wqerzn.png",
      },
      {
        id: 14,
        section: "Technical",
        name: "C Classes",
        slug: "c-classes",
        description: "Every year CSS organizes introductory to advanced-level classes in C programming for freshers taken by the CSE sophomores themselves. The aim of the programme is to provide the students with a mentor who has followed the same path as themselves and resolve the problems faced by the freshers",
        status: "upcoming",
        date: "",
        venue: "CSE Classrooms",
        event_flow: "1. Welcome & Introduction of Student Mentors\n2. Syntax & Basic Structures Briefing\n3. Coding Practice on Local Editors\n4. Daily Assignments Discussions\n5. Q&A/Doubt Clearance Session",
        organizer: "Computer Science Society",
        registrationLink: null,
        "poster-url": "https://res.cloudinary.com/dx8jytou0/image/upload/f_webp/v1757499598/istockphoto-615714450-612x612_jp54vq.jpg",
      },
    ],
  },
};

export default eventsContent;